# Built with Jekyll 3.6.0

# Setup
title:               Yujing Ren
tagline:             'Personal Blogs'
description:         Hi, you've reached Yujing Ren's Blogs. Feel free to go around and contact me!
url:                 'https://imrenyujing.github.io/'
baseurl:             '/yujinghome'

# About/contact
author:
  name:              Yujing Ren
  url:               https://sites.google.com/view/yujingren
  email:             renyj at pku.edu.cn

# Color scheme. Options: red, orange, magenta, cyan, blue, brown, darkblue
color-scheme: darkblue

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor
  - ed..gemspec
  - Gemfile
  - Gemfile.lock
  - backstop_data
  - backstop.json

# Theme
# (Used for local or custom-server deployments)
# Uncomment the `theme` line if using the Ed. theme gem on your own computer or server.
# See https://jekyllrb.com/docs/themes/
# theme: "ed."

# Remote Theme
# (Used only for GitHub deployments)
# See https://help.github.com/en/articles/adding-a-jekyll-theme-to-your-github-pages-site
remote_theme: minicomp/ed
